name: Lua Style Check

on: [ push, pull_request ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.TOMM_TOKEN }}
          version: latest
          # CLI arguments
          args: --check .
